//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hikaya.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class StoryResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal StoryResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Hikaya.Resources.StoryResource", typeof(StoryResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AdminMessagesTitle.
        /// </summary>
        public static string AdminMessagesTitle {
            get {
                return ResourceManager.GetString("AdminMessagesTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ManageStories.
        /// </summary>
        public static string AdminStoriesTitle {
            get {
                return ResourceManager.GetString("AdminStoriesTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ApplicationName.
        /// </summary>
        public static string ApplicationName {
            get {
                return ResourceManager.GetString("ApplicationName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Areyousure?.
        /// </summary>
        public static string Areyousure {
            get {
                return ResourceManager.GetString("Areyousure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back.
        /// </summary>
        public static string Back {
            get {
                return ResourceManager.GetString("Back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to backtolist.
        /// </summary>
        public static string backtolist {
            get {
                return ResourceManager.GetString("backtolist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to By.
        /// </summary>
        public static string By {
            get {
                return ResourceManager.GetString("By", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create
        ///CreateStory.
        /// </summary>
        public static string Create {
            get {
                return ResourceManager.GetString("Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create a new story.
        /// </summary>
        public static string CreateStory {
            get {
                return ResourceManager.GetString("CreateStory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PostDate.
        /// </summary>
        public static string Date {
            get {
                return ResourceManager.GetString("Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Story has beeb Deleted Successfuly.
        /// </summary>
        public static string DeleteSavedStoryMessage {
            get {
                return ResourceManager.GetString("DeleteSavedStoryMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DeleteStory.
        /// </summary>
        public static string DeleteStory {
            get {
                return ResourceManager.GetString("DeleteStory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Details.
        /// </summary>
        public static string Details {
            get {
                return ResourceManager.GetString("Details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FeedbackMessage.
        /// </summary>
        public static string FeedbackMessage {
            get {
                return ResourceManager.GetString("FeedbackMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FeedBackSendMessage.
        /// </summary>
        public static string FeedBackSendMessage {
            get {
                return ResourceManager.GetString("FeedBackSendMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image.
        /// </summary>
        public static string Image {
            get {
                return ResourceManager.GetString("Image", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inbox.
        /// </summary>
        public static string Inbox {
            get {
                return ResourceManager.GetString("Inbox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Massage.
        /// </summary>
        public static string Massage {
            get {
                return ResourceManager.GetString("Massage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message.
        /// </summary>
        public static string Message {
            get {
                return ResourceManager.GetString("Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MessageId.
        /// </summary>
        public static string MessageId {
            get {
                return ResourceManager.GetString("MessageId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MessageText.
        /// </summary>
        public static string MessageText {
            get {
                return ResourceManager.GetString("MessageText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MySavedStories.
        /// </summary>
        public static string MySavedStories {
            get {
                return ResourceManager.GetString("MySavedStories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PostDate.
        /// </summary>
        public static string PostDate {
            get {
                return ResourceManager.GetString("PostDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Publish.
        /// </summary>
        public static string Publish {
            get {
                return ResourceManager.GetString("Publish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to published.
        /// </summary>
        public static string published {
            get {
                return ResourceManager.GetString("published", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PublishedMessage.
        /// </summary>
        public static string PublishedMessage {
            get {
                return ResourceManager.GetString("PublishedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PulisherName.
        /// </summary>
        public static string PulisherName {
            get {
                return ResourceManager.GetString("PulisherName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Read.
        /// </summary>
        public static string Read {
            get {
                return ResourceManager.GetString("Read", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saved.
        /// </summary>
        public static string Saved {
            get {
                return ResourceManager.GetString("Saved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SavedForLater.
        /// </summary>
        public static string SavedForLater {
            get {
                return ResourceManager.GetString("SavedForLater", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SavedStory.
        /// </summary>
        public static string SavedStory {
            get {
                return ResourceManager.GetString("SavedStory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        public static string Search {
            get {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send.
        /// </summary>
        public static string Send {
            get {
                return ResourceManager.GetString("Send", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SendMessage.
        /// </summary>
        public static string SendMessage {
            get {
                return ResourceManager.GetString("SendMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sort.
        /// </summary>
        public static string Sort {
            get {
                return ResourceManager.GetString("Sort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Story.
        /// </summary>
        public static string Story {
            get {
                return ResourceManager.GetString("Story", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Story has beeb added Successfuly.
        /// </summary>
        public static string StoryAddedMessage {
            get {
                return ResourceManager.GetString("StoryAddedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to StoryId.
        /// </summary>
        public static string StoryId {
            get {
                return ResourceManager.GetString("StoryId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to StoryPlot.
        /// </summary>
        public static string StoryPlot {
            get {
                return ResourceManager.GetString("StoryPlot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Story has beeb Published Successfuly.
        /// </summary>
        public static string storyPublishedMessage {
            get {
                return ResourceManager.GetString("storyPublishedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Story has beeb SavedSuccessfuly.
        /// </summary>
        public static string StorySavedMessage {
            get {
                return ResourceManager.GetString("StorySavedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tags.
        /// </summary>
        public static string Tags {
            get {
                return ResourceManager.GetString("Tags", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text.
        /// </summary>
        public static string Text {
            get {
                return ResourceManager.GetString("Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title.
        /// </summary>
        public static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UserId.
        /// </summary>
        public static string UserId {
            get {
                return ResourceManager.GetString("UserId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string WriterName {
            get {
                return ResourceManager.GetString("WriterName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to YourMessage.
        /// </summary>
        public static string YourMessage {
            get {
                return ResourceManager.GetString("YourMessage", resourceCulture);
            }
        }
    }
}
